from enum import Enum


class TokenType(Enum):
    LEFT_PAREN = 'LEFT_PAREN'
    RIGHT_PAREN = 'RIGHT_PAREN'
    COMMA = 'COMMA'
    ASSIGN = 'ASSIGN'
    PLUS = 'PLUS'
    MINUS = 'MINUS'
    ASTERISK = 'ASTERISK'
    SLASH = 'SLASH'
    CARET = 'CARET'
    TILDE = 'TILDE'
    BANG = 'BANG'
    QUESTION = 'QUESTION'
    COLON = 'COLON'
    NAME = 'NAME'
    EOF = 'EOF'

    def punctuator(self) -> str | None:
        """Gets the text of a punctuator token.

        If the TokenType represents a punctuator (i.e. a token that can split an
        identifier like '+', this will get its text.
        """
        return _punctuators.get(self, None)


_punctuators = {
    TokenType.LEFT_PAREN: '(',
    TokenType.RIGHT_PAREN: ')',
    TokenType.COMMA: ',',
    TokenType.ASSIGN: '=',
    TokenType.PLUS: '+',
    TokenType.MINUS: '-',
    TokenType.ASTERISK: '*',
    TokenType.SLASH: '/',
    TokenType.CARET: '^',
    TokenType.TILDE: '~',
    TokenType.BANG: '!',
    TokenType.QUESTION: '?',
    TokenType.COLON: ':',
}


class Token:
    """A simple token class. These are generated by Lexer and consumed by Parser."""
    def __init__(self, type_: TokenType, text: str):
        self.type = type_
        self.text = text

    def __str__(self):
        return f"[{self.text},{self.type}]"


if __name__ == '__main__':
    t = Token(TokenType.NAME, 'asdf')
    print(t)
